# Generated by Django 5.0.6 on 2024-07-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_extenduser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='last_name'),
        ),
    ]
