# Generated by Django 5.0.6 on 2024-07-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_extenduser_email_alter_extenduser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
