# Generated by Django 5.0.6 on 2024-07-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_payment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userprogress',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_user_course_progress'),
        ),
    ]
