# Generated by Django 5.0.6 on 2024-07-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprogress_unique_user_course_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='completed_lessons',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='completed_lessons',
            field=models.ManyToManyField(to='users.lesson'),
        ),
    ]
