# Generated by Django 5.0.6 on 2024-07-07 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_userprogress_completed_lessons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='completed_lessons',
            field=models.ManyToManyField(limit_choices_to={'course': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.course')}, to='users.lesson'),
        ),
    ]
