# Generated by Django 5.0.6 on 2024-07-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userprogress_completed_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='completed_lessons',
            field=models.ManyToManyField(to='users.lesson'),
        ),
    ]
