# Generated by Django 5.0.6 on 2024-07-08 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_userprogress_completed_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_midterm',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='passed_quiz',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='quiz_50_percent_done',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.course'),
        ),
    ]
