# Generated by Django 5.0.6 on 2024-07-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_quiz_is_midterm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quiz',
            name='Questions',
            field=models.ManyToManyField(blank=True, to='users.question'),
        ),
    ]
