# Generated by Django 5.0.6 on 2024-07-08 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_question_quiz_quiz_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='Questions',
            new_name='Question',
        ),
    ]
