# Generated by Django 5.0.6 on 2024-07-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_questions_quiz_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='Question',
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='quizzes', to='users.question'),
        ),
    ]
